age_str = str(input("tell me your age: "))
age_int = int(age_str)
print(f"you are currently {age_int} years old.")
print(f"In 10 years, you will be{ age_int+ 10}")
print(f"In 20 years, you will be{ age_int+ 20}")
print(f"In 30 years, you will be{ age_int+ 30}")
